---
- name: Deploy
  hosts: web
  become: true
  gather_facts: true
  vars:
    # Docker role variable
    docker_daemon_options:
      exec-opts:
        - "native.cgroupdriver=systemd"
      log-driver: "json-file"
      log-opts:
        max-size: "100m"
      data-root: "/var/docker/lib"
    docker_users:
      - ubuntu
    # Backup role variables
    restic_user: "root"
    restic_group: "root"
    restic_version: 0.13.1
    google_service_account: ""
    restic_user_home: ""
    restic_repository: "rclone:gdrive:backup"
    restic_password: SUPERSECRETA
    # Backup timer configuration
    restic_backup_systemd_timer_on_calender: '*-*-* 01:00:00'
    restic_clean_systemd_timer_on_calender: '*-*-* 03:00:00'
    restic_backups_dirs:
      - path: '/home/ubuntu'
        exclude:
          - pattern: '*.log'
          - pattern: '.cache'
          - pattern: 'mywebsite'
          - pattern: 'matomo/db'
          - pattern: 'matomo/www-data/*'
          - pattern: '!matomo/www-data/config'
          - pattern: 'remark42/var/*'
          - pattern: '!remark42/var/backup'
      - path: '/etc/restic'
      - path: '/root'
        exclude:
          - pattern: '.cache'
          - pattern: '*.log'
          - pattern: 'snap'
    restic_enable_pre_backup_scripts: true
    restic_pre_backup_script:
      - name: matomo_mysql_backup.sh
        content: "{{ lookup('file', 'files/matomo_mysql_backup.sh') }}"
    rclone_install: true
    rclone_configure: true
    rclone_config_file: |
      [gdrive]
      type = drive
      scope = drive
      service_account_file = {{ restic_user_home }}/.gdrive/google_service_account.json
      team_drive =
      shared_with_me = true

  pre_tasks:
    - name: Load service account json file
      set_fact:
        google_service_account: "{{ lookup('file','files/google_service_account.json') | from_json }}"
    - name: Get Home directory of restic_user
      getent:
        database: passwd
        key: "{{ restic_user }}"
        split: ":"
    - name: Set restic user home directory
      set_fact:
        restic_user_home: "{{ getent_passwd[restic_user][4] }}"
    - name: Create gdrive config directory
      file:
        path: "{{ restic_user_home }}/.gdrive"
        state: directory
        owner: "{{ restic_user }}"
        group: "{{ restic_group }}"
        mode: 0750
    - name: Copy service account json file to rclone config directory
      copy:
        dest: "{{ restic_user_home }}/.gdrive/google_service_account.json"
        content: "{{ google_service_account | to_nice_json }}"
        owner: "{{ restic_user }}"
        group: "{{ restic_user }}"
        mode: 0644

  roles:
    - role: ricsanfre.docker
    - role: ricsanfre.backup
